# Workflow Version: 1.0.0
name: Markdownlint Check

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  markdownlint-check:
    uses: ./.github/workflows/markdownlint.yml
    with:
      runner: central-actions-example-runner
    secrets: inherit
