# Workflow Version: 1.0.0
name: Shellcheck

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  shellcheck-check:
    uses: ./.github/workflows/shellcheck.yml
    with:
      runner: central-actions-example-runner
    secrets: inherit
