# Workflow Version: 1.0.0
name: Yamllint Check

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  yamllint-check:
    uses: ./.github/workflows/yamllint.yml
    with:
      runner: central-actions-example-runner
    secrets: inherit
