# Workflow Version: 1.0.3
---
name: YamlLint

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: Runner to use

jobs:
  yamllint:
    name: yamllint
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          reporter: github-pr-review
          fail_on_error: "true"
          yamllint_flags: "-c .linters/yaml-linter.yml ."
